using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
using UnityEngine;
using WintryVR.Core;
using WintryVR.Networking;

namespace WintryVR.AssetGeneration.Providers
{
    /// <summary>
    /// Concept-art generation through an OpenAI-compatible <c>/images/generations</c> endpoint (or a backend
    /// proxy returning {data:[{b64_json}]} / {data:[{url}]}). The returned image is the concept the user
    /// confirms; look parameters are derived from the prompt and the image's dominant colour with the same
    /// heuristics as the mock provider. 3D generation belongs to a future provider; this one reports
    /// Supports3DModels=false honestly.
    /// </summary>
    public class HttpImageGenerationProvider : IAssetGenerationProvider
    {
        private readonly string _baseUrl;
        private readonly string _apiKey;
        private readonly string _model;

        public HttpImageGenerationProvider(string baseUrl, string apiKey, string model = "gpt-image-1")
        {
            _baseUrl = string.IsNullOrEmpty(baseUrl) ? "https://api.openai.com/v1" : baseUrl.TrimEnd('/');
            _apiKey = apiKey; _model = model;
        }

        public string Name => "HttpImageGen";
        public bool IsConfigured => !string.IsNullOrEmpty(_apiKey) || _baseUrl.Contains("192.168.") || _baseUrl.Contains("localhost");
        public bool RequiresNetwork => true;
        public bool SupportsConceptImages => true;
        public bool Supports3DModels => false;

        public async Task<ConceptResult> GenerateConceptAsync(string prompt, WintryLookDefinition coreIdentity, CancellationToken ct)
        {
            var result = new ConceptResult { Prompt = prompt };
            string fullPrompt = "Concept art of Wintry, a small friendly futuristic AI companion: teardrop body, rounded head with dark visor, two luminous lens eyes, floating halo ring. Premium, minimal, elegant, not gaming. Style request: " + prompt + ". Plain dark background, centered, single character.";
            var body = new Dictionary<string, object> { ["model"] = _model, ["prompt"] = fullPrompt, ["n"] = 1, ["size"] = "1024x1024" };
            var headers = new Dictionary<string, string>();
            if (!string.IsNullOrEmpty(_apiKey)) headers["Authorization"] = "Bearer " + _apiKey;
            var http = await HttpClientService.PostJsonAsync(_baseUrl + "/images/generations", MiniJson.Serialize(body), headers, 90, ct);
            if (!http.Success) { result.Error = http.Error; return result; }
            var root = MiniJson.Deserialize(http.Body);
            string b64 = MiniJson.Path(root, "data.0.b64_json") as string;
            string url = MiniJson.Path(root, "data.0.url") as string;
            byte[] png = null;
            if (!string.IsNullOrEmpty(b64)) png = Convert.FromBase64String(b64);
            else if (!string.IsNullOrEmpty(url))
            {
                var img = await HttpClientService.GetAsync(url, null, 60, ct);
                if (img.Success) png = img.Bytes;
            }
            if (png == null) { result.Error = "No image in response"; return result; }
            result.ConceptImage = await MainThreadDispatcher.RunAsync(() => { var t = new Texture2D(2, 2); t.LoadImage(png); t.name = "Concept"; return t; });
            result.Look = MockAssetGenerationProvider.LookFromPrompt(prompt, coreIdentity);
            try
            {
                var small = await MainThreadDispatcher.RunAsync(() => result.ConceptImage.GetPixels32());
                Color avg = Color.black; int n = 0;
                for (int i = 0; i < small.Length; i += 97) { Color c = small[i]; if (c.grayscale > 0.15f) { avg += c; n++; } }
                if (n > 0) { avg /= n; result.Look.PrimaryColor = Color.Lerp(result.Look.PrimaryColor, avg, 0.5f); }
            }
            catch { }
            result.Description = "Concept generated by " + _model;
            result.Success = true;
            return result;
        }

        public Task<Mesh> GenerateMeshAsync(string prompt, CancellationToken ct) => Task.FromResult<Mesh>(null);
    }
}
